# GitHub Actions - CI for Go with just builders and tests.
# https://github.com/x448/float16/blob/master/.github/workflows/ci.yml 
# Use cover.yml for coverage and safer-golangci-lint.yml for linting.
name: ci
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

# Revoke default permissions.
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  # Test on various OS and go versions.
  tests:
    name: test ${{matrix.os}} go-${{ matrix.go-version }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        go-version: [1.17, 1.23, 1.24]  # oldest supported version and latest 2 versions
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - name: Install Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build project
      run: go build ./...

    - name: Run tests
      run: |
        go version
        go test -short -race -v ./...
